### PR TITLE
feat: add Projects Obsidian Plugin supports

### LINKED ISSUE #1: [Enhancement] A way for the tool to export it for "Projects for Obsidian"
Idea:
Have the export format ready for non-kanban plugin format

I tried the [Projects for Obsidian](https://github.com/marcusolsson/obsidian-projects) plugin (which also has Kanban board view), but that seems to works a bit different and more inline with Obsidian "standards".

### PR DESCRIPTION
**Pull request by rancoud**
## How Projects Obsidian Plugin works?
Each Trello card is converted as a new note with specific header e.g.:
```
---
due: 2023-01-02
closed: 2023-01-01
status: Todo
tags: [my-tag]
---
```
* `due` datetime, it is the due date you can see in calendar view
* `closed` datetime, when card was closed
* `status`: text, list name in Trello
* `tags`: text separate by comma, labels in Trello

When clicking on `process` button, you will have to wait a little before downloading zip file called `trello-2-projects-obsidian.zip`.

It embed JSZip v3.10.1 (https://github.com/Stuk/jszip) to generate the zip file with all notes.

close #1

### CODE REVIEW

**Comment by zenminimalist** [comment]
Wow, that was fast. Thanks so much! I've just tested it and looks good so far. See this quick screen recording.

CleanShot 2023-07-30 at 16 59 05

Would it be possible to have the descriptions imported as well? That would be killer. The imported notes themselves contain that info in the note view, but not the frontmatter part, which is the part the Projects plugin uses, I believe. 

The Kanban plugin puts the `description` part all in the title, which is OK, but I find that bloated, but the projects plugin is a bit more flexible, where one can hide and unhide individual colums.  ☺️ With the projects plugin the `description` would be a separate field just like `due`, `date`, etc. that the user can then hide or unhide based on the preferences. 

Also, a nice addition (not super critical) for both plugins (Kanban and Projects) to have would be to have the sort order imported as well. So, the order it's displayed in Trello would be reflected in Obsidian. 

Not sure if Trello provides this info in their json, but I know that json contains unbelievable amounts (or columns) of data (some that's completely useless outside of Trello). But then again, I'm not certain how or if the plugins handle this - if that is even possible.

**Comment by rancoud** [comment]
I added `description` in frontmatter, but there is some limitations:
- no multiline allowed
- can't show a new line with `\n` or `<br>`
- plugin only show first 170 characters of the description
- must remove character `:` to avoid error

I also added lists and cards position given by trello in two new properties in frontmatter:
- list-order
- card-order

To apply that order you need to add two sort rules in the board view:
Obsidian_G8SzjNuNob

**Comment by zenminimalist** [comment]
Nice, thanks for the great work! Works on my end. I think now, nobody has an excuse _not_ to move  their Trello boards to Obsidian 😊

CleanShot 2023-07-31 at 14 48 22

Unfortunately, I did notice the limitations frontmatter has with certain characters and other limitations in my other lists.

**Comment by rancoud** [comment]
Thanks, I can merge that Pull Request.

**Pull request merged**
